// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2aGLZqhQ9D1Xk6WkyxU4ALwB2QVWnXE',
    appId: '1:302903046355:web:7b164124615ebb2162a426',
    messagingSenderId: '302903046355',
    projectId: 'smartexpense-tracker-project',
    authDomain: 'smartexpense-tracker-project.firebaseapp.com',
    storageBucket: 'smartexpense-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-JaO-22UV67wGCT6Yx5AZbs-OJlgqAc',
    appId: '1:302903046355:android:1419b3361656b50262a426',
    messagingSenderId: '302903046355',
    projectId: 'smartexpense-tracker-project',
    storageBucket: 'smartexpense-tracker-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmggkGdZjg5YM7ubS6ywAHmECBG-Q7K94',
    appId: '1:302903046355:ios:938ce7428bc05fa362a426',
    messagingSenderId: '302903046355',
    projectId: 'smartexpense-tracker-project',
    storageBucket: 'smartexpense-tracker-project.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmggkGdZjg5YM7ubS6ywAHmECBG-Q7K94',
    appId: '1:302903046355:ios:938ce7428bc05fa362a426',
    messagingSenderId: '302903046355',
    projectId: 'smartexpense-tracker-project',
    storageBucket: 'smartexpense-tracker-project.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_2aGLZqhQ9D1Xk6WkyxU4ALwB2QVWnXE',
    appId: '1:302903046355:web:50c594ac3077549362a426',
    messagingSenderId: '302903046355',
    projectId: 'smartexpense-tracker-project',
    authDomain: 'smartexpense-tracker-project.firebaseapp.com',
    storageBucket: 'smartexpense-tracker-project.firebasestorage.app',
  );
}
